custombucket = "mybucketforpgp"
table = "myTB"
databasehost = "mydatabase.cn62cqm4shh2.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "puranik1997"
s3database = "myDB"
kapp = "http://3.228.220.21/"
